#!/usr/bin/env bash

# Create a certificate using mkcert. Assumes you have installed mkcert previously.
# Will add the CA to the truststore for macOS, Firefox and Java.

set -e

# colours
YELLOW='\033[1;33m'
NC='\033[0m' # no colour - reset console colour

if type -p java > /dev/null ; then
  # ensure JAVA_HOME is set for mkcert to install local root CA in the java trust store
  # see https://github.com/FiloSottile/mkcert#supported-root-stores
  if test -z ${JAVA_HOME} ; then
    if [[ $(uname -s) == Darwin ]] ; then
      echo -e "☕️ Running macOS and JAVA_HOME is not set. Attempting to set it..."
      export JAVA_HOME=$(/usr/libexec/java_home)
      echo -e "✅ JAVA_HOME now set to ${JAVA_HOME}"
    else
      echo -e "☕️ Java is installed but JAVA_HOME is not set. Set it before running this script."
      exit 1
    fi
  fi
else
  echo -e "☕️ Did not detect an installation of Java."
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

NGINX_HOME=$("${DIR}/locate-nginx")
CERT_DIRECTORY=$HOME/.gu/mkcert

FORCE=no
DOMAIN=""
while [[ $# != 0 ]] ; do
  case "$1" in
    --force)
      FORCE=yes
      ;;
    *)
      DOMAIN="$1"
      ;;
  esac
  shift
done

if [[ "$DOMAIN" == "" ]] ; then
  echo -e "Create a certificate for ${YELLOW}development use only${NC} using mkcert."
  echo -e "See https://github.com/FiloSottile/mkcert for more information."
  echo
  echo "Example usage: $0 [--force] foo.local"
  exit 1
fi

KEY_FILE=${CERT_DIRECTORY}/${DOMAIN}.key
CERT_FILE=${CERT_DIRECTORY}/${DOMAIN}.crt

# test certificate has been created, and installed, and does not expire in next 14 days
if [[ "$FORCE" == no ]] && \
  [[ -r "$CERT_FILE" ]] && \
  [[ -r "${NGINX_HOME}/${DOMAIN}.crt" ]] && \
  >/dev/null 2>&1 openssl x509 -in "$CERT_FILE" -noout -checkend 1209600
then
  echo -e "🔐 Found existing certificate for: ${YELLOW}${DOMAIN}${NC}"
  echo -e "Rerun with --force to recreate if needed."
else
  mkcert -install

  echo -e "🔐 Creating certificate for: ${YELLOW}${DOMAIN}${NC}"
  mkdir -p ${CERT_DIRECTORY}
  mkcert -key-file=${KEY_FILE} -cert-file=${CERT_FILE} ${DOMAIN}

  echo -e "Symlinking the certificate for nginx at ${NGINX_HOME}"
  ln -sf ${KEY_FILE} ${NGINX_HOME}/${DOMAIN}.key
  ln -sf ${CERT_FILE} ${NGINX_HOME}/${DOMAIN}.crt

  echo -e "🚀 ${YELLOW}Done. Please restart nginx.${NC}"
fi
