#!/usr/bin/env bash

set -e

# colours
YELLOW='\033[1;33m'
NC='\033[0m' # no colour - reset console colour

GRACEFUL=false

function printHelp() {
  echo "Starts nginx. Will fail if nginx is already running."
  echo "  Flags:"
  echo "    -g | --graceful ignore nginx if it's already running"
  echo "    -h | --help     print this message"
  exit 0
}

while test $# -gt 0; do
  case "$1" in
    -g|--graceful)
      GRACEFUL=true
      shift
      ;;
    -h|--help)
      printHelp
      shift
      ;;
    *)
      break
      ;;
  esac
done

if pgrep 'nginx' > /dev/null; then
  if [ "$GRACEFUL" = true ] ; then
    exit 0
  else
    echo -e "Error: nginx already running. Did you mean ${YELLOW}dev-nginx restart${NC} or ${YELLOW}dev-nginx start -g${NC}?"
    exit 1
  fi
else
  echo -e "${YELLOW}Starting nginx. This requires sudo access.${NC}"
  sudo nginx
fi
