#!/usr/bin/env bash

set -e

# colours
YELLOW='\033[1;33m'
NC='\033[0m' # no colour - reset console colour

IGNORE_IF_ALREADY_RUNNING=false

while test $# -gt 0; do
  case "$1" in
    -i|--ignore-if-already-running)
      IGNORE_IF_ALREADY_RUNNING=true
      shift
      ;;
    *)
      break
      ;;
  esac
done

if pgrep 'nginx' > /dev/null; then
  echo "nginx already running"
  if [ "$IGNORE_IF_ALREADY_RUNNING" = false ] ; then
    echo -e "Did you mean ${YELLOW}dev-nginx start -i${NC} or ${YELLOW}dev-nginx restart${NC}?"
    exit 1
  fi
else
  echo -e "${YELLOW}Starting nginx. This requires sudo access.${NC}"
  sudo nginx
fi

